/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionItem: typeof import('./components/atoms/ActionItem.vue')['default']
    ActionList: typeof import('./components/atoms/ActionList.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BaseButton: typeof import('./components/atoms/BaseButton.vue')['default']
    CEPInputWithValidation: typeof import('./components/molecules/CEPInputWithValidation.vue')['default']
    CepSearch: typeof import('./components/CepSearch.vue')['default']
    Components: typeof import('./components/index.vue')['default']
    DialogConfirmDelete: typeof import('./components/organisms/DialogConfirmDelete.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InputCEP: typeof import('./components/atoms/InputCEP.vue')['default']
    MyListComponent: typeof import('./components/atoms/MyListComponent.vue')['default']
    MyListItem: typeof import('./components/atoms/MyListItem.vue')['default']
    ResultItem: typeof import('./components/atoms/ResultItem.vue')['default']
    ResultsList: typeof import('./components/molecules/ResultsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/organisms/SearchBar.vue')['default']
    SearchResultItem: typeof import('./components/molecules/SearchResultItem.vue')['default']
    SearchResultsList: typeof import('./components/organisms/SearchResultsList.vue')['default']
    SearchTemplate: typeof import('./components/templates/SearchTemplate.vue')['default']
    TheSnackbar: typeof import('./components/atoms/TheSnackbar.vue')['default']
  }
}
